class_name Sfx
extends Node
## Plays the placeholder sound effects from audio/sfx/ (generated by tools/make_sfx.py).
## A small pool of players, so overlapping sounds don't cut each other off. The pitch is set
## per play, which is how the count-up escalates.

const FOLDER := "res://audio/sfx"
const SOUNDS := [
	"scan",
	"bonus",
	"stamp",
	"print",
	"denied",
	"fizzle",
	"tag",
	"link",
	"copy",
	"total",
	"pass",
	"fail",
	"miss",
	"tick",
	"click",
]
const POOL_SIZE := 10

var _streams: Dictionary = {}
var _players: Array[AudioStreamPlayer] = []
var _next: int = 0


func _ready() -> void:
	for sound: String in SOUNDS:
		_streams[sound] = load("%s/%s.wav" % [FOLDER, sound])
	for i: int in range(POOL_SIZE):
		var player: AudioStreamPlayer = AudioStreamPlayer.new()
		add_child(player)
		_players.append(player)


func play(sound: String, pitch: float = 1.0, volume_db: float = 0.0) -> void:
	var stream: AudioStream = _streams.get(sound) as AudioStream
	if stream == null or _players.is_empty():
		return
	var player: AudioStreamPlayer = _players[_next]
	_next = (_next + 1) % _players.size()
	player.stream = stream
	player.pitch_scale = clampf(pitch, 0.5, 3.0)
	player.volume_db = volume_db
	player.play()
